version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "cn-north-1"
    AWS_REGION: "cn-north-1"
phases:
  install:
    runtime-versions: 
        docker: 18
  pre_build:
      commands:
        - rolearn=$(aws sts get-caller-identity | jq -r .Arn | cut -d/ -f1-2 | sed -e 's#assumed-role#role#g')
        - aws sts assume-role --role-arn $rolearn --role-session-name mysession > session.json
        - echo "AWS_ACCESS_KEY_ID=$(cat session.json | jq -r .Credentials.AccessKeyId)" > envfile
        - echo "AWS_SECRET_ACCESS_KEY=$(cat session.json | jq -r .Credentials.SecretAccessKey)" >> envfile
        - echo "AWS_SESSION_TOKEN=$(cat session.json | jq -r .Credentials.SessionToken)" >> envfile
  build:
      commands:
        - echo "touching sam-layer-packaged.yaml and chmod to 777 for samcli user to write in. See http://bit.ly/2Qd5Pxy"
        - touch sam-layer-packaged.yaml && chmod 777 sam-layer-packaged.yaml
        - S3BUCKET=pahud-tmp-cn-north-1 DOCKER_MIRROR=hub-mirror.c.163.com/ make publish-new-version-to-sar-cn
  post_build:
      commands:
        - BUILT_VERSION=$(cat VERSION) 
        - aws --region ${AWS_REGION} sns publish --topic-arn $SNS_TOPIC_ARN --message "[OK] aws-lambda-layer-botocore version ${BUILT_VERSION} published to SAR us-east-1"
